### PR TITLE
fix: allow user to remove image attachment #118

### PR DESCRIPTION
**Pull request by Ryuuko**
I'm not *officially* assigned, but hope my contribution helps anywayヽ(✿ﾟ▽ﾟ)ノ.

1. follow the "convention" 

- the svg button follows the convention using svg element----'react-icons/io'. 

- change the color according to dark mode / light mode

2. the hover effect of "grow-in" may not be necessary, just add some spice, feel free to remove if too confusing

3. e.persist() in client/src/components/Messaging/ImagePicker/index.js seems to solve the crash of the ImagePicker's index.js in utils when we click the imagePicker with cancellation (i.e. without choosing anything). The crash is only visible in development.

4. The stroke might not be adjusted as small as drawn in the Issues. Maybe workable if adjust the svg path instead using the checkbox svg of the react-icons/io directly. But it might be too tedious and break the "convention" using svg/icon library.

### CODE REVIEW

**Comment by muke1908** [comment]
@Ryuuko thank you so much!

**Comment by muke1908** [comment]
@Ryuuko does this PR includes https://github.com/muke1908/chat-e2ee/issues/136 as well?

**Comment by Ryuuko** [comment]
@muke1908 no I'm aware of #136 just now

**Comment by muke1908** [comment]
@all-contributors please add @Ryuuko for code

**Pull request merged**
