### PR TITLE
style: fix Copied button misalignment on mobile browsers

### PR DESCRIPTION
**Pull request by hfdem**
photo_2024-09-24_11-48-07

### CODE REVIEW

**Comment by muke1908** [comment]
Thanks, but I thin a proper fix would be to remove text from the button and only icon. As I can see there is not enough space for text.

**Comment by hfdem** [comment]
> Thanks, but I thin a proper fix would be to remove text from the button and only icon. As I can see there is not enough space for text.

What about the QR Code next to it? Do you think it would also be better to replace it with an icon for mobile browsers?

**Comment by muke1908** [comment]
> > Thanks, but I thin a proper fix would be to remove text from the button and only icon. As I can see there is not enough space for text.
> 
> What about the QR Code next to it? Do you think it would also be better to replace it with an icon for mobile browsers?

Yes I think so.

**Comment by hfdem** [comment]
@muke1908
屏幕截图 2024-09-25 231437

**Pull request merged**
