### PR TITLE
fix three  major issues 

### PR DESCRIPTION
**Pull request by yasinpalizban**
hi my friend i fixed three issues ( Improve auto scroll experience for chat messages was solved, Store messages in session storage,  Allow to lock a chat room) . I used new version react 16 and also install npm  package like  redux  react-redux redux-thunk react-router  then   i added three route  to back-end  (channel-lock ,channel-unlock, channel-islock)  finally add new property lock to channel object  . i hope my fork help this project getting ready to final stage.

### CODE REVIEW

**Comment by muke1908** [comment]
Hi @yasinpalizban, thank you so much for your contribution. I didn't understand what the `.idea` and `inspectionProfiles` folders are for. Can you clarify?

**Comment by yasinpalizban** [comment]
> Hi @yasinpalizban, thank you so much for your contribution. I didn't understand what the `.idea` and `inspectionProfiles` folders are for. Can you clarify?

 i forgot delete .idea folder in pull request  this folder It is nothing and it's belong to IDE webStorm .
i must me remove from repo .

**Comment by yasinpalizban** [comment]
hi check my last  commit   fix: Improve auto scroll
i did some changes to code  now it's working :-)

**Comment by muke1908** [comment]
Can you please delete the unused folders and files. 
Screenshot 2023-02-23 at 10 58 10 AM

**Comment by muke1908** [comment]
closing as inactive

**Pull request closed without merging**
