### PR TITLE
Added_more_emoji

### PR DESCRIPTION
**Pull request by GJ-16**
Added extra ```emoji```

git

### CODE REVIEW

**Comment by GJ-16** [comment]
Hey @muke1908, Can I add some notification feature for new message? I guess it is not there.

**Comment by muke1908** [comment]
@GJ-16 What kind of notification are you talking about? 
There is an "Audio" notification though.

**Comment by GJ-16** [comment]
Push notification for new messages.

**Comment by muke1908** [comment]
@GJ-16 As this is mostly for short-lived messaging, I don't think that would be useful. 
Anyway, personally, I feel the browser push notification is extremely irritating from UX point of view.

**Comment by GJ-16** [comment]
Ok @muke1908. Just a thought no issues.
And for image popup enhancement do you have something in mind?

**Comment by muke1908** [comment]
> Ok @muke1908. Just a thought no issues.
> And for image popup enhancement do you have something in mind?

Maybe show it in some nice modal. Also, make sure to work nicely in mobile device.

**Comment by GJ-16** [comment]
Okay!

**Pull request merged**
