### PR TITLE
tsx extension added to the client side 

### PR DESCRIPTION
**Pull request by suman313**
I have merged all the changes made in previous commits.

### CODE REVIEW

**Comment by muke1908** [comment]
Hi @suman313 , thanks a lot for the PR. Can you please resolve the conflicts with master and check if the build script is running without error.

**Comment by suman313** [comment]
Hi, @muke1908 I have successfully run the build script. It is running without error. I have made all the necessary changes required.

**Comment by suman313** [comment]
Hi @muke1908 , could you please assist me with the doubt on how to pass the build test in this peer? Even though I have no conflict in my repository and the "npm run dev" is successful in my local repository this pr says "Some checks haven't completed yet". "build Expected — Waiting for status to be reported".

**Comment by muke1908** [comment]
Seems like there are some conflicts. Can you run the following in your branch? 
```
git remote add upstream https://github.com/muke1908/chat-e2ee.git
git fetch upstream
git merge upstream/master
```
probably you'll find conflict after this.

**Comment by muke1908** [comment]
Screenshot 2023-06-28 at 8 57 29
@suman313 there is some error

**Comment by suman313** [comment]
Hi @muke1908, thank you for letting me know about the errors. Actually, in my local repository these are warnings and they do not prevent the build script from running successfully. But I can see ci/cd is taking warnings as errors which are preventing the build from running successfully. I will fix these errors and update them.

**Pull request merged**
