### PR TITLE
ui-changes fixed-#272

### PR DESCRIPTION
**Pull request by Aditya-13**
Fixed issue #272 

Did some ui enhancements.

The background color is not covering the whole page. (Fixed)

### CODE REVIEW

**Comment by muke1908** [comment]
Hi, @Aditya-13 thanks for the PR. Can you please mention in which browser the issue is reproducible?

**Comment by Aditya-13** [comment]
Thanks for your reply, @muke1908, i tried on both firefox and brave, on both the browsers the issue persists.

**Comment by muke1908** [comment]
@Aditya-13 Seems like it's still broken.

**Comment by Aditya-13** [comment]
Hey @muke1908 , in which browser you are facing the issue?

**Comment by muke1908** [comment]
Chrome Version 112.0.5615.121 (Official Build) (arm64)

**Pull request merged**
